In [24]:
from numpy import *
import matplotlib.pyplot as plt
import math
import numbers

In [37]:
def intercept_point(w,X,y):
    z=[0]*len(X)
    intercept=[0]*len(X)
    for i in range(len(X)):
        z[i]=-(dot(w.T,X[i]))
        intercept[i]=(1/(1+math.e**(z[i])))
        #print(intercept[i])
    return (intercept)    

In [38]:
def cost_function(w,X,y):
    total=0
    m=len(X)//2
    for i in range(m):
        intercept_temp=[0]
        intercept=intercept_point(w,X,y)
        cost=(y[i][0]*math.log(intercept[i]))+((1-y[i][0])*math.log(1-intercept[i]))
        cost=cost-y[i][0]
        cost=cost*X[i]
        total+=cost
        cost=0
    total_cost=(1/m)*total
    return(total_cost)

In [27]:
def gradient_descent(X,y,total_cost,w,alpha,iterations):
    for i in range(iterations):
        w_modified,total_cost=descent_step(X,y,total_cost,w,alpha)
        #print(w_modified,total_cost)
    return(total_cost,w_modified)        

In [40]:
def descent_step(X,y,total_cost,w,alpha):
    for i in range(len(X)//2):
        w_temp0=w[0][0]-(alpha*(total_cost[0]))
        w_temp1=w[1][0]-(alpha*(total_cost[1]))
        w[0][0]=w_temp0
        w[1][0]=w_temp1
        new_total_cost=cost_function(w,X,y)
       # if (abs(new_total_cost)-abs(total_cost))<0:
        total_cost=new_total_cost
        #elif (abs(new_total_cost)-abs(total_cost))>0:
         #   break
    return(w,total_cost)       

In [41]:
if __name__=='__main__':
    
    data_source=genfromtxt("breast_cancer_2.csv",delimiter=',',skip_header=1,usecols=(6))
    X=array(data_source).reshape(len(data_source),1)
    x1=ones(len(data_source)).reshape(len(data_source),1)
    y=array(genfromtxt("breast_cancer_2.csv",delimiter=',',skip_header=1,usecols=(10))).reshape(len(data_source),1)#labels/output
    X=append(x1, X, axis=1)#data_set or training set
    w=zeros(2).reshape(2,1)#theta matrix or coefficient matrix
    w[0][0]=0.1
    w[1][0]=0.8
    
    %time intercept=intercept_point(w,X,y)
    print(len(intercept))
    alpha=0.0001
    iterations=100
    %time total_cost=cost_function(w,X,y)
    #print(totak
    print(w,total_cost)
    %time total_cost,w=gradient_descent(X,y,total_cost,w,alpha,iterations)
    print(total_cost,w,alpha)
    
    

Wall time: 34.2 ms
683
Wall time: 2.92 s
[[ 0.1]
 [ 0.8]] [-1.34236823 -5.83511715]
[[ 0.14836791]
 [ 1.00735364]] [-1.49878768 -6.33822867]
[[ 0.20247066]
 [ 1.23291427]] [-1.6790028  -6.90315961]
[[ 0.26314484]
 [ 1.4788152 ]] [-1.88458621 -7.53201175]
[[ 0.33128791]
 [ 1.74730902]] [-2.11748271 -8.2293334 ]
[[ 0.40786692]
 [ 2.04082556]] [-2.37981302 -9.0008688 ]
[[ 0.49392327]
 [ 2.36200489]] [-2.67381307 -9.85317324]
[[ 0.59057665]
 [ 2.71372271]] [ -3.0018471  -10.79351483]
[[ 0.69903031]
 [ 3.09911453]] [ -3.36643693 -11.82959885]
[[ 0.82058212]
 [ 3.52163479]] [ -3.77057838 -12.97178422]


ValueError: math domain error

[-1.34236823 -5.83511715] [[ 0.84072226]
 [ 3.59070827]] 0.0001
